DATASET:
  NAME: 'HyRANK'
  ROOT: 'E:/zzy/GAN/data/HyRANK'
  PATCH:
    HEIGHT: 11
    WIDTH: 11
    PAD_MODE: 'symmetric'
  FFT_MODE: 'H'
  HIGH_PERCENT: 0.1


DATALOADER:
  BATCH_SIZE: 128
  NUM_WORKERS: 0
  ITERATION: 156

MODEL:
  NAME: 'ddc'
  BACKBONE: 'resnet18'

CRITERION:
  ITEMS:
    - 'softmax+ce'
  WEIGHTS:
    - 1.0

OPTIMIZER:
  NAME: 'adam'
  LR: 0.001

SCHEDULER:
  NAME: 'plateau'
  MODE: 'min'
  FACTOR: 0.1
  PATIENCE: 2

EPOCHS: 20
