DATASET:
    NAME: 'PREPROCESSED_Houston'
    ROOT: 'E:/zzy/GAN/HSI_domain_adaptation/dataset/houston_preprocessed'
    AUGMENT:
      RATIO: 21
      TRANS: ''

DATALOADER:
    BATCH_SIZE: 64
    NUM_WORKERS: 0

MODEL:
    NAME: 'mcd'

CRITERION:
    ITEMS:
      - 'softmax+ce'
      - 'l1dis'
    WEIGHTS:
      - 1.0
      - 1.0

OPTIMIZER:
    NAME: 'adam'
    LR: 0.001

SCHEDULER:
    NAME: 'plateau'
    MODE: 'min'
    FACTOR: 0.1
    PATIENCE: 2

EPOCHS: 10

EPOCHFE: 4
