DATASET:
  NAME: 'ShangHang'
  ROOT: 'E:/zzy/GAN/data/ShanghaiHangzhou'
  PATCH:
    HEIGHT: 23
    WIDTH: 23
    PAD_MODE: 'symmetric'
  FFT_MODE: 'B'
  LOW_PERCENT: 0.1
  HIGH_PERCENT: 0.1


DATALOADER:
  BATCH_SIZE: 128
  NUM_WORKERS: 0
  ITERATION: 1060

MODEL:
  NAME: 'ddc'
  BACKBONE: 'fe'

CRITERION:
  ITEMS:
    - 'softmax+ce'
  WEIGHTS:
    - 1.0

OPTIMIZER:
  NAME: 'adam'
  LR: 0.001

SCHEDULER:
  NAME: 'plateau'
  MODE: 'min'
  FACTOR: 0.1
  PATIENCE: 2

EPOCHS: 5
