DATASET:
  NAME: 'ShangHang'
  ROOT: 'E:/zzy/GAN/data/ShanghaiHangzhou'
  PATCH:
    HEIGHT: 11
    WIDTH: 11
    PAD_MODE: 'symmetric'

DATALOADER:
  BATCH_SIZE: 128
  NUM_WORKERS: 0
  ITERATION: 1060

MODEL:
  NAME: 'de_fe_mmoe_dadst_shared'
  EXPERTS:
    - 'resnet18'
    - 'resnet18'

CRITERION:
  ITEMS:
    - 'softmax+ce'
    - 'cbst'
    - 'wcec'
    - 'softmax+ce'
    - 'var'
  WEIGHTS:
    - 1.0
    - 1.0
    - 0.6
    - 1.0
    - 0.7
  THRESHOLD: 0.7

OPTIMIZER:
  NAME: 'adam'
  LR: 0.001

SCHEDULER:
  NAME: 'plateau'
  MODE: 'min'
  FACTOR: 0.1
  PATIENCE: 2

EPOCHS: 5
HYPERPARAMS:
  - 2.0