DATASET:
  NAME: 'Houston'
  ROOT: 'E:/zzy/GAN/data/Houston'
  PATCH:
    HEIGHT: 23
    WIDTH: 23
    PAD_MODE: 'symmetric'
  SAMPLE_NUM: 1260
  SAMPLE_ORDER: 'average'

DATALOADER:
  BATCH_SIZE: 64
  NUM_WORKERS: 0
  ITERATION: 40

MODEL:
  NAME: 'ddc'
  BACKBONE: 'fe'

CRITERION:
  ITEMS:
    - 'softmax+ce'
    - 'cbst'
  WEIGHTS:
    - 1.0
    - 1.0
  THRESHOLD: 0.7

OPTIMIZER:
  NAME: 'adam'
  LR: 0.0005

SCHEDULER:
  NAME: 'plateau'
  MODE: 'min'
  FACTOR: 0.1
  PATIENCE: 2

EPOCHS: 30
