DATASET:
  NAME: 'ShangHang'
  ROOT: 'E:/zzy/GAN/data/ShanghaiHangzhou'
  PATCH:
    HEIGHT: 11
    WIDTH: 11
    PAD_MODE: 'symmetric'
  SAMPLE_NUM: 540
  SAMPLE_ORDER: 'average'

DATALOADER:
  BATCH_SIZE: 128
  NUM_WORKERS: 0
  ITERATION: 1060

MODEL:
  NAME: 'ddc'
  BACKBONE: 'resnet18'

CRITERION:
  ITEMS:
    - 'softmax+ce'
    - 'mmd'
  WEIGHTS:
    - 1.0
    - 1.0
  KERNEL_NUM: 5

OPTIMIZER:
  NAME: 'adam'
  LR: 0.001

SCHEDULER:
  NAME: 'plateau'
  MODE: 'min'
  FACTOR: 0.1
  PATIENCE: 2

EPOCHS: 5
