DATASET:
    NAME: 'HyRANK'
    ROOT: 'E:/zzy/GAN/data/HyRANK'
    PATCH:
        HEIGHT: 27
        WIDTH: 27
        PAD_MODE: 'symmetric'
    SAMPLE_NUM: 1800
    SAMPLE_ORDER: 'average'

DATALOADER:
    BATCH_SIZE: 16
    NUM_WORKERS: 0

MODEL:
    NAME: 'ddc'
    BACKBONE: 'fe'

CRITERION:
    ITEMS:
      - 'softmax+ce'
      - 'mmd'
    WEIGHTS:
      - 1.0
      - 1.0
    KERNEL_NUM: 1

OPTIMIZER:
    NAME: 'adam'
    LR: 0.001

SCHEDULER:
    NAME: 'plateau'
    MODE: 'min'
    FACTOR: 0.1
    PATIENCE: 2

EPOCHS: 35
