DATASET:
    NAME: 'PREPROCESSED_HyRANK'
    ROOT: 'E:/zts/dataset/hyrank_preprocessed'
    AUGMENT:
      RATIO: 1
      TRANS: ''

DATALOADER:
    BATCH_SIZE: 64
    NUM_WORKERS: 0

MODEL:
    NAME: 'ddc'

CRITERION:
    ITEMS:
      - 'softmax+ce'
    WEIGHTS:
      - 1.0

OPTIMIZER:
    NAME: 'adam'
    LR: 0.001

SCHEDULER:
    NAME: 'plateau'
    MODE: 'min'
    FACTOR: 0.1
    PATIENCE: 2

EPOCHS: 20
