DATASET:
    NAME: 'HyRANK'
    ROOT: 'E:/zzy/GAN/data/HyRANK'
    PATCH:
        HEIGHT: 27
        WIDTH: 27
        PAD_MODE: 'symmetric'


DATALOADER:
    BATCH_SIZE: 32
    NUM_WORKERS: 0
    ITERATION: 626

MODEL:
    NAME: 'ddc'
    BACKBONE: 'fe'

CRITERION:
    ITEMS:
      - 'softmax+ce'
      - 'softmax+ce+ls'
    WEIGHTS:
      - 1.0
      - 1.0
    THRESHOLD: 0.5

OPTIMIZER:
    NAME: 'adam'
    LR: 0.001

SCHEDULER:
    NAME: 'plateau'
    MODE: 'min'
    FACTOR: 0.1
    PATIENCE: 2

EPOCHS: 35
