DATASET:
  NAME: 'HyRANK'
  ROOT: 'E:/zzy/GAN/data/HyRANK'
  PATCH:
    HEIGHT: 27
    WIDTH: 27
    PAD_MODE: 'symmetric'
  SAMPLE_NUM: 1800
  SAMPLE_ORDER: 'average'

DATALOADER:
  BATCH_SIZE: 32
  NUM_WORKERS: 0
  ITERATION: 626

MODEL:
  NAME: 'mcd'
  BACKBONE: 'fe'

CRITERION:
  ITEMS:
    - 'softmax+ce'
    - 'softmax+l1dis'
  WEIGHTS:
    - 1.0
    - 1.0

OPTIMIZER:
  NAME: 'adam'
  LR: 0.001

SCHEDULER:
  NAME: 'plateau'
  MODE: 'min'
  FACTOR: 0.1
  PATIENCE: 2

EPOCHS: 20

EPOCHK: 2