DATASET:
    NAME: 'PREPROCESSED_ShangHang'
    ROOT: 'E:/zts/dataset/shanghaihangzhou_preprocessed'
    AUGMENT:
      RATIO: 3
      TRANS: ''
    PATCH:
      HEIGHT: 27
      WIDTH: 27
      PAD_MODE: 'symmetric'

DATALOADER:
    BATCH_SIZE: 64
    NUM_WORKERS: 0

MODEL:
    NAME: 'ddc'

CRITERION:
    ITEMS:
      - 'softmax+ce'
      - 'mmd'
    WEIGHTS:
      - 1.0
      - 5.0
    KERNEL_NUM: 1

OPTIMIZER:
    NAME: 'adam'
    LR: 0.001

SCHEDULER:
    NAME: 'plateau'
    MODE: 'min'
    FACTOR: 0.1
    PATIENCE: 2

EPOCHS: 5
